# -*- coding: utf-8 -*-
"""Module3.3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QTu6Es9Ukubqlz-qhvl-m48nXall4qoL
"""

import pandas as pd
from sklearn.metrics import pairwise_distances

airports = pd.read_csv("mod2_airport_name.csv")
routes = pd.read_csv("mod2_route_names.csv")

arrival_counts = routes.groupby('Destination airport').agg(
    Arrival_Count=('Destination airport', 'count'),
    Destination_Airport_ID=('Destination airport ID', 'first')
).reset_index()

temp_airport = airports[['Airport ID', 'Country']]

arrival_counts_with_country = pd.merge(
    arrival_counts,
    temp_airport,
    left_on='Destination_Airport_ID',
    right_on='Airport ID',
    how='left'
)

arrival_counts_with_country.set_index('Destination airport', inplace=True)

query_airport = "JFK"
query_value = arrival_counts_with_country.loc[query_airport, 'Arrival_Count']
temp_arrival = arrival_counts_with_country['Arrival_Count'].values.reshape(-1, 1)
euc_dist = pairwise_distances([[query_value]], temp_arrival, metric='euclidean')

distance_df = pd.DataFrame({
    'Country': arrival_counts_with_country['Country'],
    'Distance': euc_dist.flatten()
})

sorted_distance_df = distance_df.sort_values(by='Distance')
euc_top_10 = sorted_distance_df.head(10)

print("Countries with similar arrival crowd to JFK:")
print(euc_top_10)