# -*- coding: utf-8 -*-
"""Module3.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nxf8Li339Bk7xwvtY2rwUoPZWJm2859G
"""

import pandas as pd
from sklearn.metrics import pairwise_distances

airports = pd.read_csv("mod2_airport_name.csv")
routes = pd.read_csv("mod2_route_names.csv")

departure_counts = routes.groupby('Source airport').agg(
    Departure_Count=('Source airport', 'count'),
    Source_Airport_ID=('Source airport ID', 'first')
).reset_index()

temp_airport = airports[['Airport ID', 'Country']]

departure_counts_with_country = pd.merge(
    departure_counts,
    temp_airport,
    left_on='Source_Airport_ID',
    right_on='Airport ID',
    how='left'
)

departure_counts_with_country.set_index('Source airport', inplace=True)

query_airport = "JFK"
query_value = departure_counts_with_country.loc[query_airport, 'Departure_Count']
temp_dept = departure_counts_with_country['Departure_Count'].values.reshape(-1, 1)
euc_dist = pairwise_distances([[query_value]], temp_dept, metric='euclidean')

distance_df = pd.DataFrame({
    'Country': departure_counts_with_country['Country'],
    'Distance': euc_dist.flatten()
})

sorted_distance_df = distance_df.sort_values(by='Distance')
euc_top_10 = sorted_distance_df.head(10)

print("Countries with similar departure crowd to JFK:")
print(euc_top_10)